### PR TITLE
Get network details from Submariner CR

### LINKED ISSUE #1249: subctl show network should get the info from the Operator submariner-cr
**What happened**:

Even if we configured the details on the submariner CR, still subctl show networks will show missing information in some cases, example:

```
[majopela@bluehat subm-demo]$ subctl show networks

Showing network details for cluster "microk8s-cluster1":
    Discovered network details:
        Network plugin:  generic
        Service CIDRs:   [10.152.183.0/24]
        Cluster CIDRs:   []

```

```
[majopela@bluehat subm-demo]$ kubectl get Submariner submariner -n submariner-operator -o yaml
apiVersion: submariner.io/v1alpha1
kind: Submariner
metadata:
...
spec:
...
status:
  clusterCIDR: 10.1.0.0/16
....
  natEnabled: true
  networkPlugin: generic
...
  serviceCIDR: 10.152.183.0/24
```

**What you expected to happen**:

The right information grabbed from the submariner CR

**How to reproduce it (as minimally and precisely as possible)**:

Install on microk8s/ubuntu, and then use subctl show networks.

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by Jaanki**
...and from network plugins when Submariner
is not installed.

Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

### CODE REVIEW

File: pkg/subctl/cmd/show_networks.go [hunk 1]
```diff
@@ -50,14 +50,27 @@ func showNetwork(cmd *cobra.Command, args []string) {
 }
 
 func showNetworkSingleCluster(config *rest.Config) {
-	dynClient, clientSet, err := getClients(config)
-	exitOnError("Error creating clients for cluster", err)
+	submariner := getSubmarinerResource(config)
+	if submariner != nil {
+		fmt.Println("Gathering Network details from Submariner")
```
Comment (skitt) [inline pkg/subctl/cmd/show_networks.go]: This ends up being somewhat verbose in the resulting output. How about distinguishing the source when outputting the “Discovered network details” line? That way you’d get

```
Showing network details for cluster "cluster2":
    Discovered network details:
        Network plugin:  weave-net
        Service CIDRs:   [100.2.0.0/16]
        Cluster CIDRs:   [10.2.0.0/16]
```

when using network discovery directly, and

```
Showing network details for cluster "cluster1":
    Network details reported by Submariner:
        Network plugin:  weave-net
        Service CIDRs:   [100.1.0.0/16]
        Cluster CIDRs:   [10.1.0.0/16]
```

when using the information reported by Submariner.

**Review by skitt — CHANGES_REQUESTED** [review]

**Comment by nyechiel** [comment]
(Removing from the project board as this is already tracked via the parent Issue)

File: pkg/discovery/network/network.go [hunk 2]
```diff
@@ -41,13 +41,23 @@ func (cn *ClusterNetwork) Show() {
...
-		fmt.Printf("        Cluster CIDRs:   %v\n", cn.PodCIDRs)
-		if cn.GlobalCIDR != "" {
-			fmt.Printf("        Global CIDR:     %v\n", cn.GlobalCIDR)
+		details := ClusterNetwork{
+			PodCIDRs:      cn.PodCIDRs,
+			ServiceCIDRs:  cn.ServiceCIDRs,
+			NetworkPlugin: cn.NetworkPlugin,
+			GlobalCIDR:    cn.GlobalCIDR,
 		}
+		PrintDetails(details)
```
Comment (mangelajo) [inline pkg/discovery/network/network.go]:
```suggestion
		cn.Print()
```

File: pkg/discovery/network/network.go [hunk 3]
```diff
@@ -41,13 +41,23 @@ func (cn *ClusterNetwork) Show() {
...
-		fmt.Printf("        Service CIDRs:   %v\n", cn.ServiceCIDRs)
-		fmt.Printf("        Cluster CIDRs:   %v\n", cn.PodCIDRs)
-		if cn.GlobalCIDR != "" {
-			fmt.Printf("        Global CIDR:     %v\n", cn.GlobalCIDR)
+		details := ClusterNetwork{
+			PodCIDRs:      cn.PodCIDRs,
+			ServiceCIDRs:  cn.ServiceCIDRs,
+			NetworkPlugin: cn.NetworkPlugin,
+			GlobalCIDR:    cn.GlobalCIDR,
 		}
```
Comment (mangelajo) [inline pkg/discovery/network/network.go]: Why do you create a serparate object to call print details? (see next comment down ...)

File: pkg/discovery/network/network.go [hunk 4]
```diff
@@ -41,13 +41,23 @@ func (cn *ClusterNetwork) Show() {
...
+		PrintDetails(details)
+	}
+}
+
+func PrintDetails(details ClusterNetwork) {
```
Comment (mangelajo) [inline pkg/discovery/network/network.go]: This could be 
```suggestion
func (cn *ClusterNetwork) Print() {
.....
.....

```

**Review by mangelajo — CHANGES_REQUESTED** [review]

File: pkg/subctl/cmd/show_networks.go [hunk 5]
```diff
@@ -52,14 +52,26 @@ func showNetwork(cmd *cobra.Command, args []string) {
...
+	submariner := getSubmarinerResource(config)
+	if submariner != nil {
+		fmt.Println("    Discovering Network details via Submariner:")
+		clusterNetwork := network.ClusterNetwork{
+			PodCIDRs:      []string{submariner.Status.ClusterCIDR},
+			ServiceCIDRs:  []string{submariner.Status.ServiceCIDR},
+			NetworkPlugin: submariner.Status.NetworkPlugin,
+			GlobalCIDR:    submariner.Status.GlobalCIDR,
+		}
+		clusterNetwork.Show()
```
Comment (mangelajo) [inline pkg/subctl/cmd/show_networks.go]: Won't this show twice the header?

https://github.com/submariner-io/submariner-operator/blob/ddf805966b110765dbf0d9d5226cced591794d75/pkg/discovery/network/network.go#L46

You need to remove that L46 in network.go and add it before L75 on this file show_networks.go

**Review by mangelajo — CHANGES_REQUESTED** [review]

File: pkg/subctl/cmd/show_networks.go (hunk 5 above)
Comment (Jaanki) [reply pkg/subctl/cmd/show_networks.go]: I want to explicitly mention that the details were discovered from Subm CR. The current implemetion result is

```
Discovering Network details via Submariner
Discovered network details (if cn != nil)
else
No network details discovered
```

What you are suggesting might be misleading when cn == nil
The output will be
```
Discovered  network details:
No network details discovered
```

Comment (Jaanki) [reply pkg/subctl/cmd/show_networks.go]: Discovering = trying it. Process is in progress.

Discovered is already happened. Saying "No network details discovered" after saying "Discovered  network details:" is conflicting

Comment (mangelajo) [reply pkg/subctl/cmd/show_networks.go]: Can you run it with both submariner and not submariner installed and paste the output?

This will always show: fmt.Printf("    Discovered network details:\n")

I think it will be redundant.

```
Discovering Network details via Submariner:
Discovered network details:
```

File: pkg/subctl/cmd/show_networks.go [hunk 6]
```diff
@@ -52,14 +52,26 @@ func showNetwork(cmd *cobra.Command, args []string) {
...
+		submarinerClient, err := submarinerclientset.NewForConfig(config)
+		exitOnError("Unable to get the Submariner client", err)
 
-	clusterNetwork, err := network.Discover(dynClient, clientSet, submarinerClient, OperatorNamespace)
-	exitOnError("There was an error discovering network details for this cluster", err)
+		clusterNetwork, err := network.Discover(dynClient, clientSet, submarinerClient, OperatorNamespace)
+		exitOnError("There was an error discovering network details for this cluster", err)
 
-	clusterNetwork.Show()
+		clusterNetwork.Show()
```
Comment (mangelajo) [inline pkg/subctl/cmd/show_networks.go]: I would remove from the other place, and add it here only:

print ( "Discovered network details:")


subctl is already quite verbose, we don't want unnecesary information being printed or it just becomes noise.

**Review by mangelajo — CHANGES_REQUESTED** [review]

File: pkg/subctl/cmd/show_networks.go [hunk 7]
```diff
@@ -52,14 +52,26 @@ func showNetwork(cmd *cobra.Command, args []string) {
 }
 
 func showNetworkSingleCluster(config *rest.Config) {
-	dynClient, clientSet, err := getClients(config)
-	exitOnError("Error creating clients for cluster", err)
+	submariner := getSubmarinerResource(config)
+	if submariner != nil {
+		fmt.Println("    Discovering Network details via Submariner:")
```
Comment (tpantelis) [inline pkg/subctl/cmd/show_networks.go]:
```suggestion
		fmt.Println("    Discovering network details via Submariner:")
```

**Review by tpantelis — CHANGES_REQUESTED** [review]

**Comment by nyechiel** [comment]
(removing from the project board as this is being tracked via the parent Issue)

File: pkg/subctl/cmd/show_networks.go (hunk 6 above)
Comment (Jaanki) [reply pkg/subctl/cmd/show_networks.go]: @mangelajo This is the whole ouput

```
$ ./../submariner-operator/bin/subctl show networks

Showing network details for cluster "cluster1":
    Discovered network details:
        Network plugin:  generic
        Service CIDRs:   [100.1.0.0/16]
        Cluster CIDRs:   [10.1.0.0/16]

Showing network details for cluster "cluster3":
    Discovering Network details via Submariner:
    Discovered network details:
        Network plugin:  weave-net
        Service CIDRs:   [100.3.0.0/16]
        Cluster CIDRs:   [10.3.0.0/16]

Showing network details for cluster "cluster2":
    Discovering Network details via Submariner:
    Discovered network details:
        Network plugin:  weave-net
        Service CIDRs:   [100.2.0.0/16]
        Cluster CIDRs:   [10.2.0.0/16]
```

Comment (mangelajo) [reply pkg/subctl/cmd/show_networks.go]: $ ./../submariner-operator/bin/subctl show networks

Showing network details for cluster "cluster1":
    Discovered network details:
        Network plugin:  generic
        Service CIDRs:   [100.1.0.0/16]
        Cluster CIDRs:   [10.1.0.0/16]

Showing network details for cluster "cluster3":
    Discovering Network details via Submariner:
    **Discovered network details:**
        Network plugin:  weave-net
        Service CIDRs:   [100.3.0.0/16]
        Cluster CIDRs:   [10.3.0.0/16]


That's what I mean, see bold ^

Can we try something like: 

```
$ ./../submariner-operator/bin/subctl show networks

Showing network details for cluster "cluster1":
    Discovered network details:
        Network plugin:  generic
        Service CIDRs:   [100.1.0.0/16]
        Cluster CIDRs:   [10.1.0.0/16]

Showing network details for cluster "cluster3":
    Discovering Network details via Submariner:
        Network plugin:  weave-net
        Service CIDRs:   [100.3.0.0/16]
        Cluster CIDRs:   [10.3.0.0/16]

**Review by mangelajo — CHANGES_REQUESTED** [review]

File: pkg/subctl/cmd/show_networks.go (hunk 6 above)
Comment (tpantelis) [reply pkg/subctl/cmd/show_networks.go]: Why do we even need to indicate whether or not it came from the Submariner resource? Not sure that adds any value here - that just means it was discovered prior via the same code. I suggest simplifying further:

```
Showing network details for cluster "cluster1":
    Network plugin:  generic
    Service CIDRs:   [100.1.0.0/16]
    Cluster CIDRs:   [10.1.0.0/16]

Showing network details for cluster "cluster3":
    Network plugin:  weave-net
    Service CIDRs:   [100.3.0.0/16]
    Cluster CIDRs:   [10.3.0.0/16]
```

**Review by tpantelis — CHANGES_REQUESTED** [review]

File: pkg/subctl/cmd/show_networks.go (hunk 6 above)
Comment (Jaanki) [reply pkg/subctl/cmd/show_networks.go]: I just want to be explicit. It might be easier to debug. But also at the same time avoid code-duplication.

File: pkg/subctl/cmd/show_networks.go [hunk 8]
```diff
@@ -52,14 +52,33 @@ func showNetwork(cmd *cobra.Command, args []string) {
...
+		exitOnError("Unable to get the Submariner client", err)
 
+		clusterNetwork, err = network.Discover(dynClient, clientSet, submarinerClient, OperatorNamespace)
+		exitOnError("There was an error discovering network details for this cluster", err)
+	}
+	if clusterNetwork == nil {
+		fmt.Println("    No network details discovered:")
+	} else {
+		fmt.Println(msg)
+	}
```
Comment (mangelajo) [inline pkg/subctl/cmd/show_networks.go]:
```suggestion
	if clusterNetwork != nil {
		fmt.Println(msg)
	}
```

File: pkg/discovery/network/network.go [hunk 9]
```diff
@@ -40,16 +40,11 @@ type ClusterNetwork struct {
...
-		fmt.Printf("        Service CIDRs:   %v\n", cn.ServiceCIDRs)
-		fmt.Printf("        Cluster CIDRs:   %v\n", cn.PodCIDRs)
-		if cn.GlobalCIDR != "" {
-			fmt.Printf("        Global CIDR:     %v\n", cn.GlobalCIDR)
-		}
+	fmt.Printf("        Network plugin:  %s\n", cn.NetworkPlugin)
+	fmt.Printf("        Service CIDRs:   %v\n", cn.ServiceCIDRs)
+	fmt.Printf("        Cluster CIDRs:   %v\n", cn.PodCIDRs)
+	if cn.GlobalCIDR != "" {
+		fmt.Printf("        Global CIDR:     %v\n", cn.GlobalCIDR)
```
Comment (mangelajo) [inline pkg/discovery/network/network.go]:
```suggestion
	if cn == nil {
		fmt.Println("    No network details discovered")
		return
        }
        
	fmt.Printf("        Network plugin:  %s\n", cn.NetworkPlugin)
	fmt.Printf("        Service CIDRs:   %v\n", cn.ServiceCIDRs)
	fmt.Printf("        Cluster CIDRs:   %v\n", cn.PodCIDRs)
	if cn.GlobalCIDR != "" {
		fmt.Printf("        Global CIDR:     %v\n", cn.GlobalCIDR)
```

**Review by mangelajo — CHANGES_REQUESTED** [review]

**Review by mangelajo — APPROVED** [review]

**Review by skitt — APPROVED** [review]

**Comment by skitt** [comment]
Note that this will need to be squashed.

**Review by tpantelis — APPROVED** [review]
