### PR TITLE
Validate pods status

### LINKED ISSUE #1151: subctl validate: Verify if any of the Submariner pods are constantly restarting.
**What would you like to be added**:
As part of [Epic](https://github.com/submariner-io/submariner-operator/issues/1126) this issue is to verify if any of the Submariner pods have restarted a number of times which generally could imply that something is wrong either with Submariner pods or the underlying node.

### PR DESCRIPTION
**Pull request by maayanf24**
Validate that all submariner pods status is running, and pods are not
constantly restarting

Fix issue #1151

Signed-off-by: Maayan Friedman <maafried@redhat.com>

### CODE REVIEW

File: pkg/subctl/cmd/validate_deployment.go [hunk 1]
```diff
@@ -20,13 +20,14 @@ import (
...
 	"github.com/submariner-io/submariner-operator/pkg/internal/cli"
+	v1 "k8s.io/api/core/v1"
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 	"k8s.io/client-go/kubernetes"
 	"k8s.io/client-go/rest"
 )
 
 var validatePodsCmd = &cobra.Command{
-	Use:   "pods",
+	Use:   "pod-status",
```
Comment (tpantelis) [inline pkg/subctl/cmd/validate_deployment.go]: I prefer `pods` - shorter.

```suggestion
	Use:   "pods",
```

File: pkg/subctl/cmd/validate_deployment.go [hunk 2]
```diff
@@ -140,3 +145,26 @@ func CheckDaemonset(k8sClient kubernetes.Interface, namespace, daemonSetName str
 
 	return true
 }
+
+func checkPodsStatus(k8sClient kubernetes.Interface, operatorNamespace string) bool {
+	pods, _ := k8sClient.CoreV1().Pods(operatorNamespace).List(metav1.ListOptions{})
```
Comment (tpantelis) [inline pkg/subctl/cmd/validate_deployment.go]: We should check the return err.

File: pkg/subctl/cmd/validate_deployment.go [hunk 3]
```diff
@@ -140,3 +145,26 @@ func CheckDaemonset(k8sClient kubernetes.Interface, namespace, daemonSetName str
...
+		if pod.Status.Phase != v1.PodRunning {
+			message := fmt.Sprintf("Pod %q is not running. (current state is %v)", pod.Name, pod.Status.Phase)
+			status.QueueFailureMessage(message)
+			status.End(cli.Failure)
+			return false
+		}
+
+		for _, c := range pod.Status.ContainerStatuses {
+			if c.RestartCount >= 5 {
+				message := fmt.Sprintf("Pod %q is constantly restarting (restart count: %d)", pod.Name, c.RestartCount)
```
Comment (tpantelis) [inline pkg/subctl/cmd/validate_deployment.go]: This may not mean it's constantly restarting - it may have restarted 5 times over a period of hours/days/weeks for various reasons.  Perhaps we should report it as a warning if `RestartCount` > 0: "_Pod %q has restarted %d times_".

**Review by tpantelis — CHANGES_REQUESTED** [review]

File: pkg/subctl/cmd/validate_deployment.go (hunk 1 above)
Comment (maayanf24) [reply pkg/subctl/cmd/validate_deployment.go]: I think `pod-status` is better describe the action.
@sridhargaddam  - what do you think?

Comment (tpantelis) [reply pkg/subctl/cmd/validate_deployment.go]: I don't think the `status` part is necessary plus it's singular (which pod?).  I think `subctl validate pods`  is shorter, clean and properly conveys the action of verifying the existence and state of the pods.

Comment (sridhargaddam) [reply pkg/subctl/cmd/validate_deployment.go]: I'm about to modify the same file to include checks for Overlapping CIDRs. I discussed with @aswinsuryan and we felt that we can rename the command from `pods` to `deployment`. 

So basically, as part of `subctl validate deployment` we will be checking if the desired number of Submariner pods are running, the state of the Pods and if there are any issues related to Overlapping CIDRs. So, IMHO a broader term like `deployment` might be apt. If you have any suggestions based on this updated info, please comment.

Comment (tpantelis) [reply pkg/subctl/cmd/validate_deployment.go]: `deployment` crossed my mind too since we check the `Deployments` and `DaemonSets` too. Sounds good to me.

Comment (sridhargaddam) [reply pkg/subctl/cmd/validate_deployment.go]: The following PR validates the CIDRs - https://github.com/submariner-io/submariner-operator/pull/1176

File: pkg/subctl/cmd/validate_deployment.go [hunk 4]
```diff
@@ -140,3 +145,33 @@ func CheckDaemonset(k8sClient kubernetes.Interface, namespace, daemonSetName str
...
+			status.QueueFailureMessage(message)
+			status.End(cli.Failure)
+			return false
+		}
+
+		for _, c := range pod.Status.ContainerStatuses {
+			if c.RestartCount >= 5 {
+				message := fmt.Sprintf("Pod %q has restarted %d times", pod.Name, c.RestartCount)
+				status.QueueWarningMessage(message)
+				status.End(cli.Failure)
```
Comment (sridhargaddam) [inline pkg/subctl/cmd/validate_deployment.go]: Since the pod is currently in Running State and restartCount is just a Warning, I feel we can return `status.End(cli.Success)` instead of Failure.

**Review by sridhargaddam — CHANGES_REQUESTED** [review]

File: pkg/subctl/cmd/validate_deployment.go (hunk 4 above)
Comment (maayanf24) [reply pkg/subctl/cmd/validate_deployment.go]: @sridhargaddam Do you think we should still return false in this case?
maybe we should skip the return line from this loop so it will check other pods as well?

Comment (sridhargaddam) [reply pkg/subctl/cmd/validate_deployment.go]: Yes, agree with you.

**Review by mangelajo — CHANGES_REQUESTED** [review]
Just the comment by @sridhargaddam

**Review by mangelajo — APPROVED** [review]

**Comment by mangelajo** [comment]
Remember to click on the re-review icon (the looping arrows) when updating a patch:

image

So the reviewers will get notified and also get it on their review list :)

**Comment by mangelajo** [comment]
I'm clicking it for you on this one :-)

File: pkg/subctl/cmd/validate_deployment.go [hunk 5]
```diff
@@ -140,3 +145,32 @@ func CheckDaemonset(k8sClient kubernetes.Interface, namespace, daemonSetName str
...
+			status.QueueFailureMessage(message)
+			status.End(cli.Failure)
+			return false
+		}
+
+		for _, c := range pod.Status.ContainerStatuses {
+			if c.RestartCount >= 5 {
+				message := fmt.Sprintf("Pod %q has restarted %d times", pod.Name, c.RestartCount)
+				status.QueueWarningMessage(message)
+				status.End(cli.Success)
```
Comment (sridhargaddam) [inline pkg/subctl/cmd/validate_deployment.go]: I think you should move this `status.End(cli.Success)` to Line 174

Comment (mangelajo) [reply pkg/subctl/cmd/validate_deployment.go]: Oh sorry, I clicked rereview again, you were too quick @maayanf24  ^

**Review by mangelajo — CHANGES_REQUESTED** [review]
See sridhar's comment

File: pkg/subctl/cmd/validate_deployment.go (hunk 5 above)
Comment (maayanf24) [reply pkg/subctl/cmd/validate_deployment.go]: I removed `status.End(cli.Success)` from here since it's not needed.
The return value of this func will be true for this case, and then at line 99 there will be a call for `status.End(cli.Success)`

**Review by sridhargaddam — APPROVED** [review]
Thanks for addressing the comments @maayanf24

File: pkg/subctl/cmd/validate_deployment.go [hunk 6]
```diff
@@ -20,13 +20,14 @@ import (
...
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 	"k8s.io/client-go/kubernetes"
 	"k8s.io/client-go/rest"
 )
 
 var validatePodsCmd = &cobra.Command{
-	Use:   "pods",
+	Use:   "deployment",
 	Short: "Validate the submariner pods",
 	Long:  "This command checks that all the submariner pods are running",
```
Comment (tpantelis) [inline pkg/subctl/cmd/validate_deployment.go]: We should probably update the help messages as well:

```suggestion
	Short: "Validate the submariner deployment",
	Long:  "This command checks that the submariner components are properly deployed and running",
```

**Review by tpantelis — APPROVED** [review]

**Review by dfarrell07 — APPROVED** [review]

**Review by skitt — APPROVED** [review]

**Comment by sridhargaddam** [comment]
@mangelajo can you please take a re-look at the PR.

File: pkg/subctl/cmd/validate_deployment.go [hunk 7]
```diff
@@ -145,6 +146,10 @@ func checkPods(item restConfig, submariner *v1alpha1.Submariner, operatorNamespa
 		}
 	}
 
+	if !checkPodsStatus(kubeClientSet, operatorNamespace) {
+		return
```
Comment (mangelajo) [inline pkg/subctl/cmd/validate_deployment.go:150]: I have a suggestion for later PRs

Let's not stop if something fails, so we can get full diagnostic from the other remaining items.

**Review by mangelajo — APPROVED** [review]

**Comment by mangelajo** [comment]
@maayanf24 linting of the commit message fails. Everything else good.

**Comment by tpantelis** [comment]
> @maayanf24 linting of the commit message fails. Everything else good.

yeah I fixed that and re-pushed
