### PR TITLE
Fix invalid GlobalCidrRange when globalnet disabled

### LINKED ISSUE #1668: Invalid GlobalnetCidrRange during subctl deploy-broker
**What happened**:
errros when deploy broker using subctl (version: 0.10.1)

```
E1119 01:53:34.223223       1 controller.go:267] controller-runtime/manager/controller/broker "msg"="Reconciler error" "error"="invalid GlobalnetCidrRange: invalid CIDR address: " "name"="submariner-broker" "namespace"="submariner-operator" "reconciler group"="submariner.io" "reconciler kind"="Broker"
```

when globalnet is desabled, globalnetInfo.GlobalnetCidrRange is empty, 
when check net.parse(), it reports an error

```
if globalnetInfo != nil {
		if err = IsValidCIDR(globalnetInfo.GlobalnetCidrRange); err != nil {
			return fmt.Errorf("invalid GlobalnetCidrRange: %s", err)
		}
	}
```

**What you expected to happen**:
the error not occurs again.
**How to reproduce it (as minimally and precisely as possible)**:
subctl deploy-broker
**Anything else we need to know?**:

**Environment**:

- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by jinglina**
Fixes https://github.com/submariner-io/submariner-operator/issues/1668

### CODE REVIEW

**Comment by jinglina** [comment]
this pr is related to bug 
invalid GlobalnetCidrRange whne subctl deploy-broker

File: pkg/discovery/globalnet/globalnet.go [hunk 1]
```diff
@@ -408,8 +408,10 @@ func ValidateExistingGlobalNetworks(config *rest.Config, namespace string) error
 	}
 
 	if globalnetInfo != nil {
-		if err = IsValidCIDR(globalnetInfo.GlobalnetCidrRange); err != nil {
-			return fmt.Errorf("invalid GlobalnetCidrRange: %s", err)
+		if globalnetInfo.GlobalnetEnabled {
```
Comment (tpantelis) [inline pkg/discovery/globalnet/globalnet.go]: You can combine the if statements, ie:

`if globalnetInfo != nil && globalnetInfo.GlobalnetEnabled {`

**Review by tpantelis — CHANGES_REQUESTED** [review]

File: pkg/discovery/globalnet/globalnet.go (hunk 1 above)
Comment (jinglina) [reply pkg/discovery/globalnet/globalnet.go]: yes, you are right. I will fix it.

**Review by tpantelis — APPROVED** [review]

**Review by maayanf24 — APPROVED** [review]

**Review by skitt — APPROVED** [review]

**Review by sridhargaddam — APPROVED** [review]
