### PR TITLE
Stop building and testing subctl

### LINKED ISSUE #2030: Delete the `subctl`-specific code.
Delete below directories:
- [x] /cmd
- [x] /internal
- [x] scripts/subctl
- [x] code from Makefile
- [x] /pkg except /pkg/embeddedyamls (and check for any more exceptions)

and below CI Jobs

- [x] subctl.yml
- [x] cross.yml
- [x] release_subctl_on_push.yml

Part of epic [Move subctl to its own repo](https://github.com/submariner-io/enhancements/issues/89)

### PR DESCRIPTION
**Pull request by skitt**
Now that subctl is built and released from its own repository, stop
building it here. This also removes code directly-related to subctl
(pending a full clean-up once subctl itself has been cleaned up).

Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

File: scripts/kind-e2e/e2e.sh [hunk 1]
```diff
@@ -56,18 +56,18 @@ test_subctl_gather
...
+subctl benchmark latency --intra-cluster ${KUBECONFIGS_DIR}/kind-config-cluster1
 
-${DAPPER_SOURCE}/bin/subctl benchmark latency ${KUBECONFIGS_DIR}/kind-config-cluster1 ${KUBECONFIGS_DIR}/kind-config-cluster2
+subctl benchmark latency ${KUBECONFIGS_DIR}/kind-config-cluster1 ${KUBECONFIGS_DIR}/kind-config-cluster2
 
-${DAPPER_SOURCE}/bin/subctl benchmark throughput --intra-cluster ${KUBECONFIGS_DIR}/kind-config-cluster1
+subctl benchmark throughput --intra-cluster ${KUBECONFIGS_DIR}/kind-config-cluster1
 
-${DAPPER_SOURCE}/bin/subctl benchmark throughput --verbose ${KUBECONFIGS_DIR}/kind-config-cluster1 ${KUBECONFIGS_DIR}/kind-config-cluster2
+subctl benchmark throughput --verbose ${KUBECONFIGS_DIR}/kind-config-cluster1 ${KUBECONFIGS_DIR}/kind-config-cluster2
```
Comment (tpantelis) [inline scripts/kind-e2e/e2e.sh]: I think we should remove these checks (L59-70) since they test `subctl` and the `subctl`repo is also doing it.

File: scripts/kind-e2e/lib_subctl_gather_test.sh [hunk 2]
```diff
@@ -11,7 +11,7 @@ function test_subctl_gather() {
   rm -rf $out_dir
   mkdir $out_dir
 
-  ${DAPPER_SOURCE}/bin/subctl gather --dir $out_dir
+  subctl gather --dir $out_dir
```
Comment (tpantelis) [inline scripts/kind-e2e/lib_subctl_gather_test.sh]: This tests `subctl gather ` and should also be removed.

**Review by tpantelis — CHANGES_REQUESTED** [review]

File: scripts/kind-e2e/lib_subctl_gather_test.sh (hunk 2 above)
Comment (mkolesnik) [reply scripts/kind-e2e/lib_subctl_gather_test.sh]: The whole file should probably be removed?

File: scripts/kind-e2e/e2e.sh (hunk 1 above)
Comment (mkolesnik) [reply scripts/kind-e2e/e2e.sh]: I would say L53-70

**Review by mkolesnik — CHANGES_REQUESTED** [review]

**Review by Jaanki — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Comment by tpantelis** [comment]
@mkolesnik The requested changes were made  - please re-review?

**Review by mkolesnik — APPROVED** [review]
