### PR TITLE
Fix #194 Added check for broker-cluster-context parameter

### LINKED ISSUE #194: SubCtl with --service-discovery failed to join a clusterID, since kubefedctl gets wrong subdomain
SubCtl join (after deploying with --service-discovery) failed to join a clusterID "admin" (the default cluster context name when using OCP installer), since kubefedctl received ServiceAccount as **`admin-`** ("admin" with an added dash), which is not a qualified sub-domain:

```
$ cd /home/nmanos/go/src/github.com/submariner-io/submariner-operator
$ ./bin/subctl deploy-broker --service-discovery --clusterid admin

 • Deploying broker  ...
 ✓ Deploying broker
 • Creating broker-info.subm file  ...
 ✓ Creating broker-info.subm file
 ✓ A new IPSEC PSK will be generated for broker-info.subm
 • Deploying Service Discovery controller  ...
 ✓ Deploying Service Discovery controller
 ✓ Added Lighthouse entry in the openshift-dns role
 ✓ Disabled the cluster version operator
 ✓ Added Lighthouse entry in the openshift-dns-operator role
 ✓ Updated DNS operator deployment
 ✓ Restarted the DNS operator
 ✓ Created operator CRDs
 ✓ Created operator namespace: kubefed-operator
 ✓ Created operator service account
 ✓ Deployed the operator successfully
 ✓ Created lighthouse CRDs
 ✓ Created lighthouse controller

$ kubefedctl federate namespace default --kubefed-namespace kubefed-operator
I0223 13:11:21.391968    1350 federate.go:451] Resource to federate is a namespace. Given namespace will itself be the container for the federated namespace
I0223 13:11:21.598223    1350 federate.go:480] Successfully created FederatedNamespace "default/default" from Namespace

$ export KUBECONFIG=/home/nmanos/automation/ocp-install/nmanos-cluster-a/auth/kubeconfig
$ oc get crds

clusters.submariner.io                                      2020-02-23T11:08:54Z
endpoints.submariner.io                                     2020-02-23T11:08:54Z
multiclusterservices.lighthouse.submariner.io               2020-02-23T11:10:36Z

$ oc config get-contexts
CURRENT   NAME    CLUSTER            AUTHINFO   NAMESPACE
*         admin   nmanos-cluster-a   admin      

$ ./bin/subctl join --clusterid admin ./broker-info.subm --ikeport 501 --nattport 4501
* ./broker-info.subm says broker is at: https://api.nmanos-cluster-a.devcluster.openshift.com:6443
* There are 2 labeled nodes in the cluster:
  - ip-10-0-140-162.ec2.internal
  - ip-10-0-34-202.ec2.internal
 ✓ Deploying the Submariner operator 
 ✓ Deploying multi cluster service discovery 
 ✓ Updated existing Lighthouse entry in the openshift-dns role
 ✓ Updated existing Lighthouse entry in the openshift-dns-operator role
 ✓ Updated DNS operator deployment
 ✓ Restarted the DNS operator
 ✓ Created lighthouse CRDs
 ✗ Joining to Kubefed control plane 

Error joining to Kubefed control plane: kubefedctl join failed: exit status 255
F0223 13:37:39.021430    3532 join.go:126] Error: ServiceAccount "admin-" is invalid:
metadata.name: Invalid value: "admin-": 
a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

subctl version: dev
built from git commit id: 8c619fe06f3213c456093e10e48b967863e4d5a2

```

### PR DESCRIPTION
**Pull request by aswinsuryan**
Added check for broker-cluster-context parameter

Signed-off-by: Aswin Surayanarayanan <asuryana@redhat.com>

### CODE REVIEW

File: pkg/subctl/cmd/join.go [hunk 1]
```diff
@@ -112,6 +114,13 @@ func checkArgumentPassed(args []string) error {
 	return nil
 }
 
+func checkBrokerContextPassed(brokerClusterContext string) error {
```
Comment (mangelajo) [inline pkg/subctl/cmd/join.go]: This should only be checked if in combination with service discovery.

If you are not doing service discovery this parameter can be not passed.

Comment (aswinsuryan) [reply pkg/subctl/cmd/join.go]: Done. Added the check.

**Comment by mangelajo** [comment]
I'm cherry picking to stable branch
