### PR TITLE
Capture logs of crashed pod

### LINKED ISSUE #1289: subctl gather will not capture logs for crashed pods
capture logs for crashed pods which can be captured with the -p flag when using kubectl logs

### PR DESCRIPTION
**Pull request by Jaanki**
Capture logs of crashed pod

by using Previous (-p) option of PodLogOptions

The logic implemented is

```
Capture the logs with -p
if previous_pod_found
    write_logs_to_file.log.prev
else
   ignore

Capture the logs without -p on the same pod
write_logs_to_file.log
```

Closes: #1289

Signed-Off-By: Janki Chhatbar <jchhatba@redhat.com>

### CODE REVIEW

File: pkg/subctl/cmd/gather/logs.go [hunk 1]
```diff
@@ -57,7 +57,7 @@ func gatherPodLogs(podLabelSelector string, info Info) {
 }
 
 func podLogsToFile(pod *corev1.Pod, info Info) error {
-	logRequest := info.ClientSet.CoreV1().Pods(pod.Namespace).GetLogs(pod.Name, &corev1.PodLogOptions{})
+	logRequest := info.ClientSet.CoreV1().Pods(pod.Namespace).GetLogs(pod.Name, &corev1.PodLogOptions{Previous:true})
```
Comment (mangelajo) [inline pkg/subctl/cmd/gather/logs.go]: We should only use Previous:true if the request with previous:false fails.

Comment (mangelajo) [reply pkg/subctl/cmd/gather/logs.go]: I guess that we need to try L62 with previous=false, ... if that fails, then we try again with Previous:true

**Review by mangelajo — CHANGES_REQUESTED** [review]

**Comment by mangelajo** [comment]
@Jaanki thanks for looking at this so quickly!

File: pkg/subctl/cmd/gather/logs.go (hunk 1 above)
Comment (vthapar) [reply pkg/subctl/cmd/gather/logs.go]: Why not get both? We could have scenarios where a pod crashed, caused some failures but then recovered. In such cases we will want old and current logs both.

**Comment by Jaanki** [comment]
GW pod in my setup is in `CrashLoopBackOff`. This patch generates a `.log.old` file with logs from previous pod and `.log` file with logs from current pod.

Attached are the logs files generated on running `subctl gather --module=connectivity --type=logs` 

[submariner-20210423170957.zip](https://github.com/submariner-io/submariner-operator/files/6367207/submariner-20210423170957.zip)

File: pkg/subctl/cmd/gather/logs.go [hunk 2]
```diff
@@ -62,41 +61,62 @@ func gatherPodLogsByContainer(podLabelSelector, container string, info Info) {
...
-func podLogsToFile(pod *corev1.Pod, podLogOptions *corev1.PodLogOptions, info Info) error {
+func getlogs(pod *corev1.Pod, podLogOptions *corev1.PodLogOptions, info Info) error {
+	podLogOptions.Previous = true
 	logRequest := info.ClientSet.CoreV1().Pods(pod.Namespace).GetLogs(pod.Name, podLogOptions)
+	logStream, _ := logRequest.Stream()  // TODO: Check for error other than "no previous pods found"
 
-	logs, err := processLogStream(logRequest)
+	// if no previous pods found, logstream == nil, ignore it
+	if logStream != nil {
+		info.Status.QueueWarningMessage(fmt.Sprintf("found previous instances of pod %s", pod.Name))
```
Comment (Jaanki) [inline pkg/subctl/cmd/gather/logs.go]: This warning message can be omitted

Comment (mangelajo) [reply pkg/subctl/cmd/gather/logs.go]: It's ok to keep I think.

File: pkg/subctl/cmd/gather/logs.go [hunk 3]
```diff
@@ -62,41 +61,62 @@ func gatherPodLogsByContainer(podLabelSelector, container string, info Info) {
...
+		err := writeLogs(logStream, info, pod.Name, ".log.old")
+		if err != nil {
+			return err
+		}
+		defer logStream.Close()
+	}
```
Comment (mangelajo) [inline pkg/subctl/cmd/gather/logs.go]: let's make this part a function getPreviousLogs ...

File: pkg/subctl/cmd/gather/logs.go [hunk 4]
```diff
@@ -62,41 +61,62 @@ func gatherPodLogsByContainer(podLabelSelector, container string, info Info) {
...
+	podLogOptions.Previous = false
+	logRequest = info.ClientSet.CoreV1().Pods(pod.Namespace).GetLogs(pod.Name, podLogOptions)
+	logStream, err = logRequest.Stream()
+	if err != nil {
+		return errors.WithMessage(err, "error opening log stream")
+	}
+	defer logStream.Close()
+	err = writeLogs(logStream, info, pod.Name, ".log")
+	if err != nil {}
+	return nil
```
Comment (mangelajo) [inline pkg/subctl/cmd/gather/logs.go]: And this part another function:  "getExistingLogs()"

In such way we divide the function in smaller more meaningful chunks

**Review by mangelajo — CHANGES_REQUESTED** [review]
Just a nit, looks good

File: pkg/subctl/cmd/gather/logs.go [hunk 5]
```diff
@@ -62,41 +61,46 @@ func gatherPodLogsByContainer(podLabelSelector, container string, info Info) {
 	}
 }
 
-func podLogsToFile(pod *corev1.Pod, podLogOptions *corev1.PodLogOptions, info Info) error {
-	logRequest := info.ClientSet.CoreV1().Pods(pod.Namespace).GetLogs(pod.Name, podLogOptions)
+func getlogs(pod *corev1.Pod, podLogOptions *corev1.PodLogOptions, info Info) error {
```
Comment (tpantelis) [inline pkg/subctl/cmd/gather/logs.go]: This should be camel-case but why was this renamed? `get` implies it retrieves and returns something which this function doesn't. This function outputs the logs so the name should reflect that. We could rename to `outputPodLogs`.

File: pkg/subctl/cmd/gather/logs.go [hunk 6]
```diff
@@ -62,41 +61,46 @@ func gatherPodLogsByContainer(podLabelSelector, container string, info Info) {
...
+	logs = scrubSensitiveData(info, logs)
+	err = writeLogToFile(logs, podName, info, fileExtension)
+	if err != nil {
+		return err
+	}
+
+	return nil
+}
+
+func getLogsFromStream(logStream io.ReadCloser) (string, error) {
```
Comment (tpantelis) [inline pkg/subctl/cmd/gather/logs.go]:
```suggestion
func getLogFromStream(logStream io.ReadCloser) (string, error) {
```

File: pkg/subctl/cmd/gather/logs.go [hunk 7]
```diff
@@ -62,41 +61,46 @@ func gatherPodLogsByContainer(podLabelSelector, container string, info Info) {
...
 	if err != nil {
 		return err
 	}
-
 	return nil
 }
 
-func processLogStream(logrequest *rest.Request) (string, error) {
-	logStream, err := logrequest.Stream()
+func writeLogs(logStream io.ReadCloser, info Info, podName, fileExtension string) error {
```
Comment (tpantelis) [inline pkg/subctl/cmd/gather/logs.go]:
```suggestion
func writePodLogToFile(logStream io.ReadCloser, info Info, podName, fileExtension string) error {
```

File: pkg/subctl/cmd/gather/logs.go [hunk 8]
```diff
@@ -120,3 +124,39 @@ func findPods(clientSet kubernetes.Interface, byLabelSelector string) (*corev1.P
 
 	return pods, nil
 }
+
+func getPreviousLogs(pod *corev1.Pod, podLogOptions *corev1.PodLogOptions, info Info) error {
```
Comment (tpantelis) [inline pkg/subctl/cmd/gather/logs.go]: Similar to above, this doesn't retrieve/return something. Also this mutates the `podLogOptions` param so pass by value.

```suggestion
func outputPreviousPodLog(pod *corev1.Pod, podLogOptions corev1.PodLogOptions, info Info) error {
```

File: pkg/subctl/cmd/gather/logs.go [hunk 9]
```diff
@@ -120,3 +124,39 @@ func findPods(clientSet kubernetes.Interface, byLabelSelector string) (*corev1.P
...
+		err := writeLogs(logStream, info, pod.Name, ".log.old")
+		if err != nil {
+			return err
+		}
+		defer logStream.Close()
+	}
+	return nil
+}
+
+func getExistingLogs(pod *corev1.Pod, podLogOptions *corev1.PodLogOptions, info Info) error {
```
Comment (tpantelis) [inline pkg/subctl/cmd/gather/logs.go]:
```suggestion
func outputCurrentPodLog(pod *corev1.Pod, podLogOptions corev1.PodLogOptions, info Info) error {
```

File: pkg/subctl/cmd/gather/logs.go [hunk 10]
```diff
@@ -120,3 +124,39 @@ func findPods(clientSet kubernetes.Interface, byLabelSelector string) (*corev1.P
...
+	podLogOptions.Previous = true
+	logRequest := info.ClientSet.CoreV1().Pods(pod.Namespace).GetLogs(pod.Name, podLogOptions)
+	logStream, _ := logRequest.Stream()
+
+	// TODO: Check for error other than "no previous pods found"
+
+	// if no previous pods found, logstream == nil, ignore it
+	if logStream != nil {
+		info.Status.QueueWarningMessage(fmt.Sprintf("found previous instances of pod %s", pod.Name))
+		err := writeLogs(logStream, info, pod.Name, ".log.old")
```
Comment (tpantelis) [inline pkg/subctl/cmd/gather/logs.go]: "_.old_" to me kind of implies a copy of another file.  I suggest "_.log.prev_".

File: pkg/subctl/cmd/gather/logs.go [hunk 11]
```diff
@@ -120,3 +124,39 @@ func findPods(clientSet kubernetes.Interface, byLabelSelector string) (*corev1.P
 
 	return pods, nil
 }
+
+func getPreviousLogs(pod *corev1.Pod, podLogOptions *corev1.PodLogOptions, info Info) error {
+	podLogOptions.Previous = true
+	logRequest := info.ClientSet.CoreV1().Pods(pod.Namespace).GetLogs(pod.Name, podLogOptions)
+	logStream, _ := logRequest.Stream()
+
+	// TODO: Check for error other than "no previous pods found"
```
Comment (tpantelis) [inline pkg/subctl/cmd/gather/logs.go:128]: yeah we shouldn't ignore the error.

**Review by tpantelis — CHANGES_REQUESTED** [review]

File: pkg/subctl/cmd/gather/logs.go [hunk 12]
```diff
@@ -120,3 +124,39 @@ func findPods(clientSet kubernetes.Interface, byLabelSelector string) (*corev1.P
...
+
+	// if no previous pods found, logstream == nil, ignore it
+	if logStream != nil {
+		info.Status.QueueWarningMessage(fmt.Sprintf("found previous instances of pod %s", pod.Name))
```
Comment (tpantelis) [inline pkg/subctl/cmd/gather/logs.go]:
```suggestion
		info.Status.QueueWarningMessage(fmt.Sprintf("Found logs for previous instances of pod %s", pod.Name))
```

File: pkg/subctl/cmd/gather/logs.go (hunk 1 above)
Comment (Jaanki) [reply pkg/subctl/cmd/gather/logs.go]: This patch does that.

I have a operator pod that restarted once.
`
submariner-operator       submariner-operator-7979fd59bb-psg98             1/1     Running     1          35h`

And this is reflected in the output
```
⚠ Gathering operator logs 
 ✓ Found 1 pods matching label selector "name=submariner-operator"
 ⚠ Found logs for previous instances of pod submariner-operator-7979fd59bb-psg98
```
and created
cluster2_submariner-operator-7979fd59bb-psg98.log
cluster2_submariner-operator-7979fd59bb-psg98.log.prev

File: pkg/subctl/cmd/gather/logs.go (hunk 11 above)
Comment (tpantelis) [reply pkg/subctl/cmd/gather/logs.go:128]: What about the TODO here? It's not a big deal - I guess we can deal with it later.

**Review by tpantelis — APPROVED** [review]

File: pkg/subctl/cmd/gather/logs.go [hunk 13]
```diff
@@ -62,41 +61,45 @@ func gatherPodLogsByContainer(podLabelSelector, container string, info Info) {
 	}
 }
 
-func podLogsToFile(pod *corev1.Pod, podLogOptions *corev1.PodLogOptions, info Info) error {
-	logRequest := info.ClientSet.CoreV1().Pods(pod.Namespace).GetLogs(pod.Name, podLogOptions)
+func outputPodLogs(pod *corev1.Pod, podLogOptions corev1.PodLogOptions, info Info) error {
+	err := outputPreviousPodLog(pod, podLogOptions, info)
+	if err != nil {
+		return err
```
Comment (mangelajo) [inline pkg/subctl/cmd/gather/logs.go]: The problem here is that if this one fails the next one won’t even be attempted. I would save the error and return an aggregated error at the end of the function so we don’t skip the other log dumper.

**Review by mangelajo — CHANGES_REQUESTED** [review]

File: pkg/subctl/cmd/gather/logs.go (hunk 13 above)
Comment (Jaanki) [reply pkg/subctl/cmd/gather/logs.go]: yes. Good catch @mangelajo

**Review by mangelajo — APPROVED** [review]

File: pkg/subctl/cmd/gather/logs.go [hunk 14]
```diff
@@ -62,41 +61,55 @@ func gatherPodLogsByContainer(podLabelSelector, container string, info Info) {
...
+	if outputCurrentPodLogErr != nil {
+		outputPodLogsErrors = append(outputPodLogsErrors, fmt.Sprintf("error %s getting logs from current pod %s",
+			outputCurrentPodLogErr.Error(), pod.Name))
+	}
+
+	var outputPodLogsError string
+	for _, err := range outputPodLogsErrors {
+		outputPodLogsError += err + "\n" // Prints each error in a new line
+	}
+	return errors.New(outputPodLogsError)
```
Comment (tpantelis) [inline pkg/subctl/cmd/gather/logs.go]: Rather than concatenating errors, I suggest to simplify it and just output the errors directly:

```
func outputPodLogs(pod *corev1.Pod, podLogOptions corev1.PodLogOptions, info Info) {
    err := outputPreviousPodLog(pod, podLogOptions, info)
    if err != nil {
        info.Status.QueueFailureMessage(fmt.Sprintf("Error outputting previous log for pod %q: %v", pod.Name, err))		
    }

    err := outputCurrentPodLog(pod, podLogOptions, info)
    if err != nil {
        info.Status.QueueFailureMessage(fmt.Sprintf("Error outputting current log for pod %q: %v", pod.Name, err))
    }
}
```

**Review by tpantelis — CHANGES_REQUESTED** [review]

**Review by tpantelis — APPROVED** [review]
