### PR TITLE
Remove misleading OVN CNI not supported msg

### LINKED ISSUE #1288: subctl gather always complains with  ⚠ OVN CNI not supported yet, although it's supported
**What happened**:
subctl gather always complains with  ⚠ OVN CNI not supported yet, although it's supported

**What you expected to happen**:
subctl gather to successfully collect OVN data

**How to reproduce it (as minimally and precisely as possible)**:
Run `subctl gather --module=connectivity` on an environment with CNI=OVN
**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`): 0.9-rc0

### PR DESCRIPTION
**Pull request by vthapar**
OVN CNI is now handled explicitly in its own function instead of generic
`CNIResources`. Remove OVN from CNI type check in `CNIResources`

Fixes #1288

Signed-off-by: Vishal Thapar <5137689+vthapar@users.noreply.github.com>

### CODE REVIEW

File: pkg/subctl/cmd/gather/cni.go [hunk 1]
```diff
@@ -97,8 +97,6 @@ func CNIResources(info Info, networkPlugin string) {
 			switch networkPluginCNIType[networkPlugin] {
 			case typeIPTables:
 				logIPTablesCmds(info, pod)
-			case typeOvn:
```
Comment (mangelajo) [inline pkg/subctl/cmd/gather/cni.go:100]: let's keep the "typeOvn: " with no action, otherwise we will get the typeUnknown "failure".

**Review by mangelajo — CHANGES_REQUESTED** [review]
let's keep the "typeOvn: " with no action, otherwise we will get the typeUnknown "failure".

**Review by tpantelis — APPROVED** [review]

**Review by mangelajo — APPROVED** [review]
