### PR TITLE
Fix usage of kubeconfig flag in subctl verify

### LINKED ISSUE #1448: subctl verify show --kubeconfig as a flag
**What happened**:
```
./bin/subctl verify --kubeconfig output/kubeconfigs/kind-config-cluster2 output/kubeconfigs/kind-config-cluster1
Error: two kubecontexts must be specified
Usage:
  subctl verify --kubecontexts <kubeContext1>,<kubeContext2> [flags]

Flags:
      --connection-attempts uint      maximum number of connection attempts (default 2)
      --connection-timeout uint       timeout in seconds per connection attempt (default 60)
      --disruptive-tests              enable disruptive verifications like gateway-failover
  -h, --help                          help for verify
      --kubeconfig string             absolute path(s) to the kubeconfig file(s)
      --kubecontexts strings          comma separated list of kubeconfig contexts to use, can be specified multiple times.
                                      If none specified, all contexts referenced by kubeconfig are used
      --only string                   comma separated verifications to be performed (default "connectivity,service-discovery,gateway-failover")
      --operation-timeout uint        operation timeout for K8s API calls (default 240)
      --report-dir string             XML report directory (default ".")
      --submariner-namespace string   namespace in which submariner is deployed (default "submariner-operator")
      --verbose                       produce verbose logs during connectivity verification

Error:  two kubecontexts must be specified
```

**What you expected to happen**:
1. Error message should be: `Error: unknown flag: --kubeconfig`
2. `--kubeconfig` should not be in command flags list

**How to reproduce it (as minimally and precisely as possible)**:
`./bin/subctl verify --kubeconfig output/kubeconfigs/kind-config-cluster2 output/kubeconfigs/kind-config-cluster1`

**Anything else we need to know?**:

**Environment**:
subctl version: devel

### PR DESCRIPTION
**Pull request by maayanf24**
1. send kubeconfig flag to test framework so it will not be ignored
2. use a unique help text to kubecontexts flag when called from subctl
   verify

Fixes issue #1448

Signed-off-by: Maayan Friedman <maafried@redhat.com>

### CODE REVIEW

File: pkg/subctl/cmd/verify.go [hunk 1]
```diff
@@ -58,7 +58,7 @@ var (
 )
 
 func init() {
-	AddKubeContextMultiFlag(verifyCmd)
+	AddKubeContextMultiFlag(verifyCmd, "comma separated list of kubeconfig contexts to use, must specified 2 contexts.")
```
Comment (mangelajo) [inline pkg/subctl/cmd/verify.go]:
```suggestion
	AddKubeContextMultiFlag(verifyCmd, "comma separated list of kubeconfig contexts to use, 2 contexts must be specified.")
```

File: pkg/subctl/cmd/root.go [hunk 2]
```diff
@@ -80,11 +80,14 @@ func AddKubeContextFlag(cmd *cobra.Command) {
...
 // AddKubeContextMultiFlag adds a "kubeconfig" flag and a "kubecontext" flag that can be specified multiple times (or comma separated)
-func AddKubeContextMultiFlag(cmd *cobra.Command) {
+func AddKubeContextMultiFlag(cmd *cobra.Command, usage string) {
 	AddKubeConfigFlag(cmd)
-	cmd.PersistentFlags().StringSliceVar(&kubeContexts, "kubecontexts", nil,
-		"comma separated list of kubeconfig contexts to use, can be specified multiple times.\n"+
-			"If none specified, all contexts referenced by kubeconfig are used")
+	if usage == "" {
+		usage = "comma separated list of kubeconfig contexts to use, can be specified multiple times.\n" +
+			"If none specified, all contexts referenced by kubeconfig are used"
```
Comment (tpantelis) [inline pkg/subctl/cmd/root.go]:
```suggestion
		usage = "comma-separated list of kubeconfig contexts to use.\n" +
			"If none specified, all contexts referenced by the kubeconfig are used"
```

File: pkg/subctl/cmd/verify.go (hunk 1 above)
Comment (tpantelis) [inline pkg/subctl/cmd/verify.go]:
```suggestion
	AddKubeContextMultiFlag(verifyCmd, "comma separated list of exactly two kubeconfig contexts to use.")
```

**Review by tpantelis — CHANGES_REQUESTED** [review]

**Review by skitt — APPROVED** [review]
Tested locally in various combinations, everything works as expected.

**Review by mangelajo — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]
