### PR TITLE
Scrub sensitive information from gather output

### LINKED ISSUE #1257: subctl gather stores sensitive information that must be redacted (tokens & IPSEC PSK, API URLS?)
**What happened**:

`subctl gather` is designed to grab all neccesary information in submariner to raise a bug, but
that doesn't mean that a customer may want to share all his credentials & connect information
with us.

**What you expected to happen**:

PSK, Tokens & possibly URLS must be redacted in the output files.

An easy solution could be a 2nd pass of figuring out those details, and then doing replaces on all generated files for

$PSK ->  ##redacted##
$TOKEN -> ##redacted##
$API endpoint -> ##redacted##

I would make this disableable (--include-sensitive-information ? ) so the users can provide that information
if they want/need too and there's a good reason for that.

**How to reproduce it (as minimally and precisely as possible)**:

```
subctl gather

[majopela@bluehat submariner-20210416092718]$ egrep -e "PSK|TOKEN" -A 1 submariner-*/*
microk8s-cluster1_daemonsets_submariner-operator_submariner-gateway.yaml:        - name: BROKER_K8S_APISERVERTOKEN
microk8s-cluster1_daemonsets_submariner-operator_submariner-gateway.yaml-          value: eyJhbGciOiJSUzI1NiIsImtpZCI6InI3TDlobDVwVkhQeEZ0THo2QmlObEVUZ0lFTnMtbDVkTXJ6cXVJZDdaZXcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdWJtYXJpbmVyLWs4cy1icm9rZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiY2x1c3Rlci1taWNyb2s4cy1jbHVzdGVyMS10b2tlbi1mZG5kdyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJjbHVzdGVyLW1pY3JvazhzLWNsdXN0ZXIxIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZGNjZmFmNWItNTBkNy00NzNiLThjYzQtZWE4ODFlMDVmZGFhIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnN1Ym1hcmluZXItazhzLWJyb2tlcjpjbHVzdGVyLW1pY3JvazhzLWNsdXN0ZXIxIn0.WCRBDSKKzFaopCagsmDDmqFSv1Sf28yt1AlnNDOS7WMVvK152bnN4JzlgcYG8dDlp3xjktsth3WEa4uLGmBHEspviHL9wsTQzUoYFgK9GW0TFXbezRg8VHUN7gjxVZmfPvjYqZJFyR1dSprtVlS3iM6zF6hLSZUJFkLehZ-tVKq30s92Y_-Q0Rs3_GkgyR1JBMxbNkEgR7HI4Zps6Q7MZ_zQZDhF10J0uy60I9aQTOTZPp46S_J-2ve00p4AWKEvyAUQz_FNEhJn2IZj1AIFAsaEBvWBh2H46HMfVrm7w1adx8Rp8vAU2qAXHitv4Qg8Dsf4qVAFGKcXoZw11i12yQ
--
microk8s-cluster1_deployments_submariner-operator_submariner-lighthouse-agent.yaml:        - name: BROKER_K8S_APISERVERTOKEN
microk8s-cluster1_deployments_submariner-operator_submariner-lighthouse-agent.yaml-          value: eyJhbGciOiJSUzI1NiIsImtpZCI6InI3TDlobDVwVkhQeEZ0THo2QmlObEVUZ0lFTnMtbDVkTXJ6cXVJZDdaZXcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdWJtYXJpbmVyLWs4cy1icm9rZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiY2x1c3Rlci1taWNyb2s4cy1jbHVzdGVyMS10b2tlbi1mZG5kdyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJjbHVzdGVyLW1pY3JvazhzLWNsdXN0ZXIxIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZGNjZmFmNWItNTBkNy00NzNiLThjYzQtZWE4ODFlMDVmZGFhIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnN1Ym1hcmluZXItazhzLWJyb2tlcjpjbHVzdGVyLW1pY3JvazhzLWNsdXN0ZXIxIn0.WCRBDSKKzFaopCagsmDDmqFSv1Sf28yt1AlnNDOS7WMVvK152bnN4JzlgcYG8dDlp3xjktsth3WEa4uLGmBHEspviHL9wsTQzUoYFgK9GW0TFXbezRg8VHUN7gjxVZmfPvjYqZJFyR1dSprtVlS3iM6zF6hLSZUJFkLehZ-tVKq30s92Y_-Q0Rs3_GkgyR1JBMxbNkEgR7HI4Zps6Q7MZ_zQZDhF10J0uy60I9aQTOTZPp46S_J-2ve00p4AWKEvyAUQz_FNEhJn2IZj1AIFAsaEBvWBh2H46HMfVrm7w1adx8Rp8vAU2qAXHitv4Qg8Dsf4qVAFGKcXoZw11i12yQ
--
microk8s-cluster1_submariners_submariner-operator_submariner.yaml:  ceIPSecPSK: 6SqROYeI3erGPOXtfNLkygCn3E8JORJ5j6UYguWTuNKlJvqomEpaKroXvrSBL7L+
microk8s-cluster1_submariners_submariner-operator_submariner.yaml-  clusterCIDR: 10.1.0.0/16
```

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by vthapar**
Fixes #1257

Signed-off-by: Vishal Thapar <5137689+vthapar@users.noreply.github.com>

### CODE REVIEW

File: pkg/subctl/cmd/gather/resource.go [hunk 1]
```diff
@@ -60,8 +61,8 @@ func ResourcesToYAMLFile(info Info, ofType schema.GroupVersionResource, namespac
 			if err != nil {
 				return errors.WithMessage(err, "error marshaling to YAML")
 			}
-
-			_, err = file.Write(data)
+			scrubbedData := scrubSensitiveData(info, string(data))
```
Comment (mangelajo) [inline pkg/subctl/cmd/gather/resource.go:64]: can we add a flag to make it optional, enabled by default?

File: pkg/subctl/cmd/gather/resource.go [hunk 2]
```diff
@@ -98,3 +99,11 @@ func gatherConfigMaps(info Info, namespace string, listOptions metav1.ListOption
 		Resource: "configmaps",
 	}, namespace, listOptions)
 }
+
+func scrubSensitiveData(info Info, dataString string) string {
+	dataString = strings.Replace(dataString, info.Submariner.Spec.BrokerK8sApiServer, "##redeacted-api-server##", -1)
```
Comment (mangelajo) [inline pkg/subctl/cmd/gather/resource.go]: if !info.scrubData {
   return
}

? :)

**Review by mangelajo — CHANGES_REQUESTED** [review]

File: pkg/subctl/cmd/gather/resource.go (hunk 1 above)
Comment (vthapar) [reply pkg/subctl/cmd/gather/resource.go:64]: Oh yes, I had those changes but lost when messed up a rebase. will push flag soon.

File: pkg/subctl/cmd/gather/resource.go [hunk 3]
```diff
@@ -98,3 +99,13 @@ func gatherConfigMaps(info Info, namespace string, listOptions metav1.ListOption
 		Resource: "configmaps",
 	}, namespace, listOptions)
 }
+
+func scrubSensitiveData(info Info, dataString string) string {
+	if !info.IncludeSecrets {
+		dataString = strings.Replace(dataString, info.Submariner.Spec.BrokerK8sApiServer, "##redeacted-api-server##", -1)
```
Comment (tpantelis) [inline pkg/subctl/cmd/gather/resource.go]: `info.Submariner` will be nil if not installed, in which case we need to get it from `ServiceDiscovery`. It would be nice to refactor the common bits into a separate resource that is always installed. In lieu of that, I'll send a patch after this to try to handle this smoothly.

File: pkg/subctl/cmd/gather.go [hunk 4]
```diff
@@ -118,9 +121,10 @@ func gatherDataByCluster(restConfig restConfig, directory string) {
 	fmt.Printf("Gathering information from cluster %q\n", clusterName)
 
 	info := gather.Info{
-		RestConfig:  restConfig.config,
-		ClusterName: clusterName,
-		DirName:     directory,
+		RestConfig:     restConfig.config,
+		ClusterName:    clusterName,
+		DirName:        directory,
+		IncludeSecrets: includeSecrets,
```
Comment (tpantelis) [inline pkg/subctl/cmd/gather.go]:
```suggestion
		IncludeSensitiveData: includeSecrets,
```

File: pkg/subctl/cmd/gather.go [hunk 5]
```diff
@@ -31,9 +31,10 @@ import (
 )
 
 var (
-	gatherType   string
-	gatherModule string
-	directory    string
+	gatherType     string
+	gatherModule   string
+	directory      string
+	includeSecrets bool
```
Comment (tpantelis) [inline pkg/subctl/cmd/gather.go]:
```suggestion
	includeSensitiveData bool
```

File: pkg/subctl/cmd/gather.go [hunk 6]
```diff
@@ -75,6 +76,8 @@ func addGatherFlags(gatherCmd *cobra.Command) {
 	gatherCmd.Flags().StringVar(&directory, "dir", "",
 		"the directory in which to store files. If not specified, a directory of the form \"submariner-<timestamp>\" "+
 			"is created in the current directory")
+	gatherCmd.Flags().BoolVar(&includeSecrets, "include-secrets", false,
+		"do not redact sensitive data")
```
Comment (tpantelis) [inline pkg/subctl/cmd/gather.go]:
```suggestion
	gatherCmd.Flags().BoolVar(&includeSecrets, "include-sensitive-data", false,
		"do not redact sensitive data such as credentials and security tokens")
```

**Review by tpantelis — CHANGES_REQUESTED** [review]

File: pkg/subctl/cmd/gather.go (hunk 6 above)
Comment (mangelajo) [reply pkg/subctl/cmd/gather.go]: Oh, right, include-secrets sounded good to me, but sensitive-data may be is more precise. 

Anyway, simple & effective implementation thanks @vthapar !! :)

File: pkg/subctl/cmd/gather/resource.go (hunk 3 above)
Comment (vthapar) [reply pkg/subctl/cmd/gather/resource.go]: I was going to add a patch with ServiceDiscovery, plan to use that for some of lighthouse stuff and can then reuse it if Submariner is not present. Can refactor this code once that comes in.

Comment (tpantelis) [reply pkg/subctl/cmd/gather/resource.go]: I pushed #1283 - I can refactor this with that one.

**Review by tpantelis — APPROVED** [review]

**Review by mangelajo — APPROVED** [review]
