### PR TITLE
Error on invalid --image-override name

### LINKED ISSUE #1018: Overriding images with wrong keys should fail first in join command
```
$ subctl join   ./broker-info.subm --cable-driver libreswan   --ikeport 501 --nattport 4501 --enable-pod-debugging --ipsec-debug --health-check     --image-override submariner-operator=registry.gitlab.com/smattar/submariner-rhel8-operator:v0.8.0     --image-override submariner-gateway=registry.gitlab.com/smattar/submariner-gateway-rhel8:v0.8.0     --image-override submariner-route-agent=registry.gitlab.com/smattar/submariner-route-agent-rhel8:v0.8.0     --image-override submariner-globalnet=registry.gitlab.com/smattar/submariner-globalnet-rhel8:v0.8.0     --image-override submariner-networkplugin-syncer=registry.gitlab.com/smattar/submariner-networkplugin-syncer-rhel8:v0.8.0     --image-override lighthouse-agent=registry.gitlab.com/smattar/lighthouse-agent-rhel8:v0.8.0     --image-override lighthouse-coredns=registry.gitlab.com/smattar/lighthouse-coredns-rhel8:v0.8.0

https://api.nmanos-cluster-a.devcluster.openshift.com:6443
 • Discovering network details  ...
* There are 1 labeled nodes in the cluster:
  - ip-10-166-89-163.us-west-1.compute.internal
 ✓ Discovering network details
    Discovered network details:
        Network plugin:  OpenShiftSDN
        Service CIDRs:   [100.96.0.0/16]
        Cluster CIDRs:   [10.252.0.0/14]
 • Discovering multi cluster details  ...
 • Validating Globalnet configurations  ...
 ✓ Validating Globalnet configurations
 • Assigning Globalnet IPs  ...
 ✓ Assigning Globalnet IPs
 ✓ Allocated GlobalCIDR: 169.254.0.0/19
 ✓ Discovering multi cluster details
 • Deploying the Submariner operator  ...
 ✓ Deploying the Submariner operator
 ✓ Created operator CRDs
 ✓ Created operator service account and role
 ✓ Updated the privileged SCC
 ✓ Created lighthouse service account and role
 ✓ Updated the privileged SCC
 ✓ Created Lighthouse service accounts and roles
 ✓ Deployed the operator successfully
 • Creating SA for cluster  ...
 ✓ Creating SA for cluster
 • Deploying Submariner  ...
 ✓ Deploying Submariner
 ✓ Submariner is up and running
```

Subctl join seems OK, but Submariner images failed, since I used wrong key name:
 --image-override submariner-gateway=...   
instead of:
 --image-override submariner=...
```
############################## Submariner information (subctl show all) ##############################


Showing information for cluster "nmanos-cluster-a":
    Discovered network details:
        Network plugin:  OpenShiftSDN
        Service CIDRs:   [100.96.0.0/16]
        Cluster CIDRs:   [10.252.0.0/14]
        Global CIDR:     169.254.0.0/19

No resources found.

No resources found.

No resources found.

COMPONENT                       REPOSITORY                                            VERSION         
submariner                      quay.io/submariner                                    0.8.0           
submariner-operator             registry.gitlab.com/smattar/submariner-rhel8-operator v0.8.0          
service-discovery               quay.io/submariner                                    0.8.0           

Showing information for cluster "default-cl1":
    Discovered network details:
        Network plugin:  OpenShiftSDN
        Service CIDRs:   [100.96.0.0/16]
        Cluster CIDRs:   [10.252.0.0/14]
        Global CIDR:     169.254.32.0/19

No resources found.

No resources found.

No resources found.

COMPONENT                       REPOSITORY                                            VERSION         
submariner                      quay.io/submariner                                    0.8.0           
submariner-operator             registry.gitlab.com/smattar/submariner-rhel8-operator v0.8.0          
service-discovery               quay.io/submariner                                    0.8.0           

############################## Printing Submariner logs on nmanos-cluster-a ##############################

NAME                                                 READY   STATUS             RESTARTS   AGE
pod/submariner-gateway-wv7lk                         0/1     ImagePullBackOff   0          3m30s
pod/submariner-globalnet-s5696                       0/1     ImagePullBackOff   0          3m26s
pod/submariner-lighthouse-agent-5bb5fb894b-8sfbf     1/1     Running            0          3m23s
pod/submariner-lighthouse-coredns-84dd4799f6-vsqgd   1/1     Running            0          3m21s
pod/submariner-lighthouse-coredns-84dd4799f6-xj4lh   1/1     Running            0          102s
pod/submariner-operator-677668ff95-r77tv             1/1     Running            0          4m32s
pod/submariner-routeagent-2lqsv                      0/1     ImagePullBackOff   0          3m26s
pod/submariner-routeagent-2rz7c                      0/1     ImagePullBackOff   0          3m26s
pod/submariner-routeagent-4mpb7                      1/1     Running            0          3m26s
pod/submariner-routeagent-9b7gb                      1/1     Running            0          3m26s
pod/submariner-routeagent-dnqj4                      1/1     Running            0          3m26s
pod/submariner-routeagent-s789s                      0/1     ImagePullBackOff   0          3m26s
pod/submariner-routeagent-xlm86                      1/1     Running            0          3m26s
```

_Originally posted by @mangelajo in https://github.com/submariner-io/submariner-operator/issues/941#issuecomment-737094349_

### PR DESCRIPTION
**Pull request by Jaanki**
`subctl join` now errors out when an invalid image name is
passed to `--image-override` flag.

The error is in the format
Invalid image name `submariner` provided. Please choose from ["submariner-networkplugin-syncer" "submariner-route-agent" "submariner-gateway" "submariner-globalnet" "lighthouse-agent" "lighthouse-coredns" "submariner-operator"]

Depends on #1405 
Closes: #1018 
Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

### CODE REVIEW

**Review by mangelajo — APPROVED** [review]

File: pkg/subctl/cmd/join.go [hunk 1]
```diff
@@ -570,6 +570,9 @@ func getImageOverrides() map[string]string {
 		imageOverrides := make(map[string]string)
 		for _, s := range imageOverrideArr {
 			key := strings.Split(s, "=")[0]
+			if invalidImageName(key) {
+				exitOnError(fmt.Sprintf("Invalid image name provided. Please choose from %q", names.ValidImageNames), errors.New(key))
```
Comment (Jaanki) [inline pkg/subctl/cmd/join.go]:
```suggestion
				exitWithErrorMsg(fmt.Sprintf("Invalid image name provided. Please choose from %q", names.ValidImageNames), errors.New(key))
```

**Review by tpantelis — APPROVED** [review]
