### PR TITLE
gather: Use libreswan as default if none specified

### LINKED ISSUE #2065: subctl gather fails to gather libreswan data
**What happened**:
`subctl gather` fails to gather libreswan data if `CableDriver` field is missing/empty in `Submariner` Spec.

**What you expected to happen**:
If `Submariner.Spec.CableDriver` is empty, it should use libreswan as default and gather data for it.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy submariner manually with `Submariner.Spec.CableDriver` field empty.

**Anything else we need to know?**:

**Environment**:

subctl version: v0.12.0
Submariner version:  0.12.0
Kubernetes Server version: v1.23.5+9ce5071

### PR DESCRIPTION
**Pull request by vthapar**
If no cable driver is configured in SubmarinerSpec, use
`libreswan` as default when gathering data.

Fixes #2065

Signed-off-by: Vishal Thapar <5137689+vthapar@users.noreply.github.com>

### CODE REVIEW

File: internal/gather/cni.go [hunk 1]
```diff
@@ -172,7 +172,7 @@ func gatherOVNResources(info *Info, networkPlugin string) {
 
 func gatherCableDriverResources(info *Info, cableDriver string) {
 	logPodInfo(info, "cable driver data", gatewayPodLabel, func(info *Info, pod *v1.Pod) {
-		if cableDriver == libreswan {
+		if cableDriver == libreswan || cableDriver == "" { // If none specified, use libreswan as default
```
Comment (skitt) [inline internal/gather/cni.go:175]: Instead of hard-coding Libreswan as the default, ask the cable drivers what the default is:

```suggestion
		if cableDriver == libreswan || (cableDriver == "" && cable.GetDefaultCableDriver() == libreswan) {
```

**Review by skitt — CHANGES_REQUESTED** [review]

File: internal/gather/cni.go (hunk 1 above)
Comment (vthapar) [reply internal/gather/cni.go:175]: Don't think this will work. `GetDefaultCableDriver()` fetches value from a global variable that is set in submariner engine. It won't be available in subctl

Comment (skitt) [reply internal/gather/cni.go:175]: Ah yes, you’re right!

**Review by skitt — APPROVED** [review]

**Review by dfarrell07 — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Comment by sridhargaddam** [comment]
@vthapar I think we should backport this PR. Can you please handle it?

**Comment by dfarrell07** [comment]
PR scrub agrees this should be backported.
